// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: paymentSimulator/invoice/createInvoice.proto

package dto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateInvoicePaymentRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IdempotencyKey string                 `protobuf:"bytes,1,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	BookingId      string                 `protobuf:"bytes,3,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	PayerId        string                 `protobuf:"bytes,4,opt,name=payer_id,json=payerId,proto3" json:"payer_id,omitempty"`
	IssuedAt       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=issuedAt,proto3" json:"issuedAt,omitempty"`
	DueAt          *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=dueAt,proto3" json:"dueAt,omitempty"`
	Payer          *Payer                 `protobuf:"bytes,7,opt,name=payer,proto3" json:"payer,omitempty"`
	Booking        *BookingSnapshot       `protobuf:"bytes,8,opt,name=booking,proto3" json:"booking,omitempty"`
	// Amounts
	Total         *Money `protobuf:"bytes,9,opt,name=total,proto3" json:"total,omitempty"`
	TaxTotal      *Money `protobuf:"bytes,10,opt,name=tax_total,json=taxTotal,proto3" json:"tax_total,omitempty"`
	DiscountTotal *Money `protobuf:"bytes,11,opt,name=discount_total,json=discountTotal,proto3" json:"discount_total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInvoicePaymentRequest) Reset() {
	*x = CreateInvoicePaymentRequest{}
	mi := &file_paymentSimulator_invoice_createInvoice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInvoicePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInvoicePaymentRequest) ProtoMessage() {}

func (x *CreateInvoicePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paymentSimulator_invoice_createInvoice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInvoicePaymentRequest.ProtoReflect.Descriptor instead.
func (*CreateInvoicePaymentRequest) Descriptor() ([]byte, []int) {
	return file_paymentSimulator_invoice_createInvoice_proto_rawDescGZIP(), []int{0}
}

func (x *CreateInvoicePaymentRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *CreateInvoicePaymentRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *CreateInvoicePaymentRequest) GetPayerId() string {
	if x != nil {
		return x.PayerId
	}
	return ""
}

func (x *CreateInvoicePaymentRequest) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

func (x *CreateInvoicePaymentRequest) GetDueAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DueAt
	}
	return nil
}

func (x *CreateInvoicePaymentRequest) GetPayer() *Payer {
	if x != nil {
		return x.Payer
	}
	return nil
}

func (x *CreateInvoicePaymentRequest) GetBooking() *BookingSnapshot {
	if x != nil {
		return x.Booking
	}
	return nil
}

func (x *CreateInvoicePaymentRequest) GetTotal() *Money {
	if x != nil {
		return x.Total
	}
	return nil
}

func (x *CreateInvoicePaymentRequest) GetTaxTotal() *Money {
	if x != nil {
		return x.TaxTotal
	}
	return nil
}

func (x *CreateInvoicePaymentRequest) GetDiscountTotal() *Money {
	if x != nil {
		return x.DiscountTotal
	}
	return nil
}

type Payer struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email          string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	DocumentNumber string                 `protobuf:"bytes,3,opt,name=document_number,json=documentNumber,proto3" json:"document_number,omitempty"`
	BillingAddress string                 `protobuf:"bytes,4,opt,name=billing_address,json=billingAddress,proto3" json:"billing_address,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Payer) Reset() {
	*x = Payer{}
	mi := &file_paymentSimulator_invoice_createInvoice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payer) ProtoMessage() {}

func (x *Payer) ProtoReflect() protoreflect.Message {
	mi := &file_paymentSimulator_invoice_createInvoice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payer.ProtoReflect.Descriptor instead.
func (*Payer) Descriptor() ([]byte, []int) {
	return file_paymentSimulator_invoice_createInvoice_proto_rawDescGZIP(), []int{1}
}

func (x *Payer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Payer) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Payer) GetDocumentNumber() string {
	if x != nil {
		return x.DocumentNumber
	}
	return ""
}

func (x *Payer) GetBillingAddress() string {
	if x != nil {
		return x.BillingAddress
	}
	return ""
}

type BookingSnapshot struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CottageName    string                 `protobuf:"bytes,1,opt,name=cottage_name,json=cottageName,proto3" json:"cottage_name,omitempty"`
	Nights         int32                  `protobuf:"varint,2,opt,name=nights,proto3" json:"nights,omitempty"`
	NumberOfGuests int32                  `protobuf:"varint,3,opt,name=number_of_guests,json=numberOfGuests,proto3" json:"number_of_guests,omitempty"`
	ValuePerNight  *Money                 `protobuf:"bytes,4,opt,name=value_per_night,json=valuePerNight,proto3" json:"value_per_night,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BookingSnapshot) Reset() {
	*x = BookingSnapshot{}
	mi := &file_paymentSimulator_invoice_createInvoice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingSnapshot) ProtoMessage() {}

func (x *BookingSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_paymentSimulator_invoice_createInvoice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingSnapshot.ProtoReflect.Descriptor instead.
func (*BookingSnapshot) Descriptor() ([]byte, []int) {
	return file_paymentSimulator_invoice_createInvoice_proto_rawDescGZIP(), []int{2}
}

func (x *BookingSnapshot) GetCottageName() string {
	if x != nil {
		return x.CottageName
	}
	return ""
}

func (x *BookingSnapshot) GetNights() int32 {
	if x != nil {
		return x.Nights
	}
	return 0
}

func (x *BookingSnapshot) GetNumberOfGuests() int32 {
	if x != nil {
		return x.NumberOfGuests
	}
	return 0
}

func (x *BookingSnapshot) GetValuePerNight() *Money {
	if x != nil {
		return x.ValuePerNight
	}
	return nil
}

var File_paymentSimulator_invoice_createInvoice_proto protoreflect.FileDescriptor

const file_paymentSimulator_invoice_createInvoice_proto_rawDesc = "" +
	"\n" +
	",paymentSimulator/invoice/createInvoice.proto\x12\x18paymentSimulator.invoice\x1a#paymentSimulator/common/money.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa0\x04\n" +
	"\x1bCreateInvoicePaymentRequest\x12'\n" +
	"\x0fidempotency_key\x18\x01 \x01(\tR\x0eidempotencyKey\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x03 \x01(\tR\tbookingId\x12\x19\n" +
	"\bpayer_id\x18\x04 \x01(\tR\apayerId\x126\n" +
	"\bissuedAt\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt\x120\n" +
	"\x05dueAt\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x05dueAt\x125\n" +
	"\x05payer\x18\a \x01(\v2\x1f.paymentSimulator.invoice.PayerR\x05payer\x12C\n" +
	"\abooking\x18\b \x01(\v2).paymentSimulator.invoice.BookingSnapshotR\abooking\x124\n" +
	"\x05total\x18\t \x01(\v2\x1e.paymentSimulator.common.MoneyR\x05total\x12;\n" +
	"\ttax_total\x18\n" +
	" \x01(\v2\x1e.paymentSimulator.common.MoneyR\btaxTotal\x12E\n" +
	"\x0ediscount_total\x18\v \x01(\v2\x1e.paymentSimulator.common.MoneyR\rdiscountTotal\"\x83\x01\n" +
	"\x05Payer\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12'\n" +
	"\x0fdocument_number\x18\x03 \x01(\tR\x0edocumentNumber\x12'\n" +
	"\x0fbilling_address\x18\x04 \x01(\tR\x0ebillingAddress\"\xbe\x01\n" +
	"\x0fBookingSnapshot\x12!\n" +
	"\fcottage_name\x18\x01 \x01(\tR\vcottageName\x12\x16\n" +
	"\x06nights\x18\x02 \x01(\x05R\x06nights\x12(\n" +
	"\x10number_of_guests\x18\x03 \x01(\x05R\x0enumberOfGuests\x12F\n" +
	"\x0fvalue_per_night\x18\x04 \x01(\v2\x1e.paymentSimulator.common.MoneyR\rvaluePerNightB@Z>github.com/Kenji-Uema/paymentSimulator/internal/domain/dto;dtob\x06proto3"

var (
	file_paymentSimulator_invoice_createInvoice_proto_rawDescOnce sync.Once
	file_paymentSimulator_invoice_createInvoice_proto_rawDescData []byte
)

func file_paymentSimulator_invoice_createInvoice_proto_rawDescGZIP() []byte {
	file_paymentSimulator_invoice_createInvoice_proto_rawDescOnce.Do(func() {
		file_paymentSimulator_invoice_createInvoice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_paymentSimulator_invoice_createInvoice_proto_rawDesc), len(file_paymentSimulator_invoice_createInvoice_proto_rawDesc)))
	})
	return file_paymentSimulator_invoice_createInvoice_proto_rawDescData
}

var file_paymentSimulator_invoice_createInvoice_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_paymentSimulator_invoice_createInvoice_proto_goTypes = []any{
	(*CreateInvoicePaymentRequest)(nil), // 0: paymentSimulator.invoice.CreateInvoicePaymentRequest
	(*Payer)(nil),                       // 1: paymentSimulator.invoice.Payer
	(*BookingSnapshot)(nil),             // 2: paymentSimulator.invoice.BookingSnapshot
	(*timestamppb.Timestamp)(nil),       // 3: google.protobuf.Timestamp
	(*Money)(nil),                       // 4: paymentSimulator.common.Money
}
var file_paymentSimulator_invoice_createInvoice_proto_depIdxs = []int32{
	3, // 0: paymentSimulator.invoice.CreateInvoicePaymentRequest.issuedAt:type_name -> google.protobuf.Timestamp
	3, // 1: paymentSimulator.invoice.CreateInvoicePaymentRequest.dueAt:type_name -> google.protobuf.Timestamp
	1, // 2: paymentSimulator.invoice.CreateInvoicePaymentRequest.payer:type_name -> paymentSimulator.invoice.Payer
	2, // 3: paymentSimulator.invoice.CreateInvoicePaymentRequest.booking:type_name -> paymentSimulator.invoice.BookingSnapshot
	4, // 4: paymentSimulator.invoice.CreateInvoicePaymentRequest.total:type_name -> paymentSimulator.common.Money
	4, // 5: paymentSimulator.invoice.CreateInvoicePaymentRequest.tax_total:type_name -> paymentSimulator.common.Money
	4, // 6: paymentSimulator.invoice.CreateInvoicePaymentRequest.discount_total:type_name -> paymentSimulator.common.Money
	4, // 7: paymentSimulator.invoice.BookingSnapshot.value_per_night:type_name -> paymentSimulator.common.Money
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_paymentSimulator_invoice_createInvoice_proto_init() }
func file_paymentSimulator_invoice_createInvoice_proto_init() {
	if File_paymentSimulator_invoice_createInvoice_proto != nil {
		return
	}
	file_paymentSimulator_common_money_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_paymentSimulator_invoice_createInvoice_proto_rawDesc), len(file_paymentSimulator_invoice_createInvoice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_paymentSimulator_invoice_createInvoice_proto_goTypes,
		DependencyIndexes: file_paymentSimulator_invoice_createInvoice_proto_depIdxs,
		MessageInfos:      file_paymentSimulator_invoice_createInvoice_proto_msgTypes,
	}.Build()
	File_paymentSimulator_invoice_createInvoice_proto = out.File
	file_paymentSimulator_invoice_createInvoice_proto_goTypes = nil
	file_paymentSimulator_invoice_createInvoice_proto_depIdxs = nil
}
