// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: paymentSimulator/payment/paymentConfirmation.proto

package dto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentConfirmation struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PaymentIntentId string                 `protobuf:"bytes,2,opt,name=payment_intent_id,json=paymentIntentId,proto3" json:"payment_intent_id,omitempty"`
	BookingId       string                 `protobuf:"bytes,4,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	Amount          *Money                 `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Method          PaymentMethod          `protobuf:"varint,6,opt,name=method,proto3,enum=paymentSimulator.common.PaymentMethod" json:"method,omitempty"`
	ReceiptId       string                 `protobuf:"bytes,7,opt,name=receipt_id,json=receiptId,proto3" json:"receipt_id,omitempty"`
	Card            *CardSummary           `protobuf:"bytes,8,opt,name=card,proto3" json:"card,omitempty"`
	ConfirmedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=confirmed_at,json=confirmedAt,proto3" json:"confirmed_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PaymentConfirmation) Reset() {
	*x = PaymentConfirmation{}
	mi := &file_paymentSimulator_payment_paymentConfirmation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentConfirmation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentConfirmation) ProtoMessage() {}

func (x *PaymentConfirmation) ProtoReflect() protoreflect.Message {
	mi := &file_paymentSimulator_payment_paymentConfirmation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentConfirmation.ProtoReflect.Descriptor instead.
func (*PaymentConfirmation) Descriptor() ([]byte, []int) {
	return file_paymentSimulator_payment_paymentConfirmation_proto_rawDescGZIP(), []int{0}
}

func (x *PaymentConfirmation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PaymentConfirmation) GetPaymentIntentId() string {
	if x != nil {
		return x.PaymentIntentId
	}
	return ""
}

func (x *PaymentConfirmation) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *PaymentConfirmation) GetAmount() *Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *PaymentConfirmation) GetMethod() PaymentMethod {
	if x != nil {
		return x.Method
	}
	return PaymentMethod_PAYMENT_METHOD_UNSPECIFIED
}

func (x *PaymentConfirmation) GetReceiptId() string {
	if x != nil {
		return x.ReceiptId
	}
	return ""
}

func (x *PaymentConfirmation) GetCard() *CardSummary {
	if x != nil {
		return x.Card
	}
	return nil
}

func (x *PaymentConfirmation) GetConfirmedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ConfirmedAt
	}
	return nil
}

var File_paymentSimulator_payment_paymentConfirmation_proto protoreflect.FileDescriptor

const file_paymentSimulator_payment_paymentConfirmation_proto_rawDesc = "" +
	"\n" +
	"2paymentSimulator/payment/paymentConfirmation.proto\x12\x1bpaymentSimulator.payment.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a#paymentSimulator/common/money.proto\x1a+paymentSimulator/common/paymentMethod.proto\x1a)paymentSimulator/common/cardSummary.proto\"\x80\x03\n" +
	"\x13PaymentConfirmation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12*\n" +
	"\x11payment_intent_id\x18\x02 \x01(\tR\x0fpaymentIntentId\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x04 \x01(\tR\tbookingId\x126\n" +
	"\x06amount\x18\x05 \x01(\v2\x1e.paymentSimulator.common.MoneyR\x06amount\x12>\n" +
	"\x06method\x18\x06 \x01(\x0e2&.paymentSimulator.common.PaymentMethodR\x06method\x12\x1d\n" +
	"\n" +
	"receipt_id\x18\a \x01(\tR\treceiptId\x128\n" +
	"\x04card\x18\b \x01(\v2$.paymentSimulator.common.CardSummaryR\x04card\x12=\n" +
	"\fconfirmed_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\vconfirmedAtB@Z>github.com/Kenji-Uema/paymentSimulator/internal/domain/dto;dtob\x06proto3"

var (
	file_paymentSimulator_payment_paymentConfirmation_proto_rawDescOnce sync.Once
	file_paymentSimulator_payment_paymentConfirmation_proto_rawDescData []byte
)

func file_paymentSimulator_payment_paymentConfirmation_proto_rawDescGZIP() []byte {
	file_paymentSimulator_payment_paymentConfirmation_proto_rawDescOnce.Do(func() {
		file_paymentSimulator_payment_paymentConfirmation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_paymentSimulator_payment_paymentConfirmation_proto_rawDesc), len(file_paymentSimulator_payment_paymentConfirmation_proto_rawDesc)))
	})
	return file_paymentSimulator_payment_paymentConfirmation_proto_rawDescData
}

var file_paymentSimulator_payment_paymentConfirmation_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_paymentSimulator_payment_paymentConfirmation_proto_goTypes = []any{
	(*PaymentConfirmation)(nil),   // 0: paymentSimulator.payment.v1.PaymentConfirmation
	(*Money)(nil),                 // 1: paymentSimulator.common.Money
	(PaymentMethod)(0),            // 2: paymentSimulator.common.PaymentMethod
	(*CardSummary)(nil),           // 3: paymentSimulator.common.CardSummary
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_paymentSimulator_payment_paymentConfirmation_proto_depIdxs = []int32{
	1, // 0: paymentSimulator.payment.v1.PaymentConfirmation.amount:type_name -> paymentSimulator.common.Money
	2, // 1: paymentSimulator.payment.v1.PaymentConfirmation.method:type_name -> paymentSimulator.common.PaymentMethod
	3, // 2: paymentSimulator.payment.v1.PaymentConfirmation.card:type_name -> paymentSimulator.common.CardSummary
	4, // 3: paymentSimulator.payment.v1.PaymentConfirmation.confirmed_at:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_paymentSimulator_payment_paymentConfirmation_proto_init() }
func file_paymentSimulator_payment_paymentConfirmation_proto_init() {
	if File_paymentSimulator_payment_paymentConfirmation_proto != nil {
		return
	}
	file_paymentSimulator_common_money_proto_init()
	file_paymentSimulator_common_paymentMethod_proto_init()
	file_paymentSimulator_common_cardSummary_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_paymentSimulator_payment_paymentConfirmation_proto_rawDesc), len(file_paymentSimulator_payment_paymentConfirmation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_paymentSimulator_payment_paymentConfirmation_proto_goTypes,
		DependencyIndexes: file_paymentSimulator_payment_paymentConfirmation_proto_depIdxs,
		MessageInfos:      file_paymentSimulator_payment_paymentConfirmation_proto_msgTypes,
	}.Build()
	File_paymentSimulator_payment_paymentConfirmation_proto = out.File
	file_paymentSimulator_payment_paymentConfirmation_proto_goTypes = nil
	file_paymentSimulator_payment_paymentConfirmation_proto_depIdxs = nil
}
