// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: paymentSimulator/payment/paymentMakingCard.proto

package dto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentStatus int32

const (
	PaymentStatus_PAYMENT_STATUS_UNSPECIFIED PaymentStatus = 0
	PaymentStatus_PAYMENT_STATUS_PENDING     PaymentStatus = 1
	PaymentStatus_PAYMENT_STATUS_SUCCEEDED   PaymentStatus = 2
	PaymentStatus_PAYMENT_STATUS_FAILED      PaymentStatus = 3
	PaymentStatus_PAYMENT_STATUS_EXPIRED     PaymentStatus = 4
	PaymentStatus_PAYMENT_STATUS_CANCELLED   PaymentStatus = 5
)

// Enum value maps for PaymentStatus.
var (
	PaymentStatus_name = map[int32]string{
		0: "PAYMENT_STATUS_UNSPECIFIED",
		1: "PAYMENT_STATUS_PENDING",
		2: "PAYMENT_STATUS_SUCCEEDED",
		3: "PAYMENT_STATUS_FAILED",
		4: "PAYMENT_STATUS_EXPIRED",
		5: "PAYMENT_STATUS_CANCELLED",
	}
	PaymentStatus_value = map[string]int32{
		"PAYMENT_STATUS_UNSPECIFIED": 0,
		"PAYMENT_STATUS_PENDING":     1,
		"PAYMENT_STATUS_SUCCEEDED":   2,
		"PAYMENT_STATUS_FAILED":      3,
		"PAYMENT_STATUS_EXPIRED":     4,
		"PAYMENT_STATUS_CANCELLED":   5,
	}
)

func (x PaymentStatus) Enum() *PaymentStatus {
	p := new(PaymentStatus)
	*p = x
	return p
}

func (x PaymentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_paymentSimulator_payment_paymentMakingCard_proto_enumTypes[0].Descriptor()
}

func (PaymentStatus) Type() protoreflect.EnumType {
	return &file_paymentSimulator_payment_paymentMakingCard_proto_enumTypes[0]
}

func (x PaymentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentStatus.Descriptor instead.
func (PaymentStatus) EnumDescriptor() ([]byte, []int) {
	return file_paymentSimulator_payment_paymentMakingCard_proto_rawDescGZIP(), []int{0}
}

// request
type PayWithCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Card          *Card                  `protobuf:"bytes,1,opt,name=card,proto3" json:"card,omitempty"`
	InvoiceNumber string                 `protobuf:"bytes,2,opt,name=invoice_number,json=invoiceNumber,proto3" json:"invoice_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayWithCardRequest) Reset() {
	*x = PayWithCardRequest{}
	mi := &file_paymentSimulator_payment_paymentMakingCard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayWithCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayWithCardRequest) ProtoMessage() {}

func (x *PayWithCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paymentSimulator_payment_paymentMakingCard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayWithCardRequest.ProtoReflect.Descriptor instead.
func (*PayWithCardRequest) Descriptor() ([]byte, []int) {
	return file_paymentSimulator_payment_paymentMakingCard_proto_rawDescGZIP(), []int{0}
}

func (x *PayWithCardRequest) GetCard() *Card {
	if x != nil {
		return x.Card
	}
	return nil
}

func (x *PayWithCardRequest) GetInvoiceNumber() string {
	if x != nil {
		return x.InvoiceNumber
	}
	return ""
}

type Card struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Brand         string                 `protobuf:"bytes,1,opt,name=brand,proto3" json:"brand,omitempty"`
	Number        string                 `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
	ExpMonth      uint32                 `protobuf:"varint,3,opt,name=exp_month,json=expMonth,proto3" json:"exp_month,omitempty"`
	ExpYear       uint32                 `protobuf:"varint,4,opt,name=exp_year,json=expYear,proto3" json:"exp_year,omitempty"`
	Cvv           string                 `protobuf:"bytes,5,opt,name=cvv,proto3" json:"cvv,omitempty"`
	HolderName    string                 `protobuf:"bytes,6,opt,name=holder_name,json=holderName,proto3" json:"holder_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Card) Reset() {
	*x = Card{}
	mi := &file_paymentSimulator_payment_paymentMakingCard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_paymentSimulator_payment_paymentMakingCard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_paymentSimulator_payment_paymentMakingCard_proto_rawDescGZIP(), []int{1}
}

func (x *Card) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *Card) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *Card) GetExpMonth() uint32 {
	if x != nil {
		return x.ExpMonth
	}
	return 0
}

func (x *Card) GetExpYear() uint32 {
	if x != nil {
		return x.ExpYear
	}
	return 0
}

func (x *Card) GetCvv() string {
	if x != nil {
		return x.Cvv
	}
	return ""
}

func (x *Card) GetHolderName() string {
	if x != nil {
		return x.HolderName
	}
	return ""
}

// response
type PayWithCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReceiptNumber string                 `protobuf:"bytes,1,opt,name=receipt_number,json=receiptNumber,proto3" json:"receipt_number,omitempty"`
	InvoiceNumber string                 `protobuf:"bytes,2,opt,name=invoice_number,json=invoiceNumber,proto3" json:"invoice_number,omitempty"`
	Status        PaymentStatus          `protobuf:"varint,3,opt,name=status,proto3,enum=paymentSimulator.payment.v1.PaymentStatus" json:"status,omitempty"`
	Card          *CardSummary           `protobuf:"bytes,4,opt,name=card,proto3" json:"card,omitempty"`
	ProcessedAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=processed_at,json=processedAt,proto3" json:"processed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayWithCardResponse) Reset() {
	*x = PayWithCardResponse{}
	mi := &file_paymentSimulator_payment_paymentMakingCard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayWithCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayWithCardResponse) ProtoMessage() {}

func (x *PayWithCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paymentSimulator_payment_paymentMakingCard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayWithCardResponse.ProtoReflect.Descriptor instead.
func (*PayWithCardResponse) Descriptor() ([]byte, []int) {
	return file_paymentSimulator_payment_paymentMakingCard_proto_rawDescGZIP(), []int{2}
}

func (x *PayWithCardResponse) GetReceiptNumber() string {
	if x != nil {
		return x.ReceiptNumber
	}
	return ""
}

func (x *PayWithCardResponse) GetInvoiceNumber() string {
	if x != nil {
		return x.InvoiceNumber
	}
	return ""
}

func (x *PayWithCardResponse) GetStatus() PaymentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentStatus_PAYMENT_STATUS_UNSPECIFIED
}

func (x *PayWithCardResponse) GetCard() *CardSummary {
	if x != nil {
		return x.Card
	}
	return nil
}

func (x *PayWithCardResponse) GetProcessedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ProcessedAt
	}
	return nil
}

var File_paymentSimulator_payment_paymentMakingCard_proto protoreflect.FileDescriptor

const file_paymentSimulator_payment_paymentMakingCard_proto_rawDesc = "" +
	"\n" +
	"0paymentSimulator/payment/paymentMakingCard.proto\x12\x1bpaymentSimulator.payment.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a)paymentSimulator/common/cardSummary.proto\"r\n" +
	"\x12PayWithCardRequest\x125\n" +
	"\x04card\x18\x01 \x01(\v2!.paymentSimulator.payment.v1.CardR\x04card\x12%\n" +
	"\x0einvoice_number\x18\x02 \x01(\tR\rinvoiceNumber\"\x9f\x01\n" +
	"\x04Card\x12\x14\n" +
	"\x05brand\x18\x01 \x01(\tR\x05brand\x12\x16\n" +
	"\x06number\x18\x02 \x01(\tR\x06number\x12\x1b\n" +
	"\texp_month\x18\x03 \x01(\rR\bexpMonth\x12\x19\n" +
	"\bexp_year\x18\x04 \x01(\rR\aexpYear\x12\x10\n" +
	"\x03cvv\x18\x05 \x01(\tR\x03cvv\x12\x1f\n" +
	"\vholder_name\x18\x06 \x01(\tR\n" +
	"holderName\"\xa0\x02\n" +
	"\x13PayWithCardResponse\x12%\n" +
	"\x0ereceipt_number\x18\x01 \x01(\tR\rreceiptNumber\x12%\n" +
	"\x0einvoice_number\x18\x02 \x01(\tR\rinvoiceNumber\x12B\n" +
	"\x06status\x18\x03 \x01(\x0e2*.paymentSimulator.payment.v1.PaymentStatusR\x06status\x128\n" +
	"\x04card\x18\x04 \x01(\v2$.paymentSimulator.common.CardSummaryR\x04card\x12=\n" +
	"\fprocessed_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vprocessedAt*\xbe\x01\n" +
	"\rPaymentStatus\x12\x1e\n" +
	"\x1aPAYMENT_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16PAYMENT_STATUS_PENDING\x10\x01\x12\x1c\n" +
	"\x18PAYMENT_STATUS_SUCCEEDED\x10\x02\x12\x19\n" +
	"\x15PAYMENT_STATUS_FAILED\x10\x03\x12\x1a\n" +
	"\x16PAYMENT_STATUS_EXPIRED\x10\x04\x12\x1c\n" +
	"\x18PAYMENT_STATUS_CANCELLED\x10\x05B@Z>github.com/Kenji-Uema/paymentSimulator/internal/domain/dto;dtob\x06proto3"

var (
	file_paymentSimulator_payment_paymentMakingCard_proto_rawDescOnce sync.Once
	file_paymentSimulator_payment_paymentMakingCard_proto_rawDescData []byte
)

func file_paymentSimulator_payment_paymentMakingCard_proto_rawDescGZIP() []byte {
	file_paymentSimulator_payment_paymentMakingCard_proto_rawDescOnce.Do(func() {
		file_paymentSimulator_payment_paymentMakingCard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_paymentSimulator_payment_paymentMakingCard_proto_rawDesc), len(file_paymentSimulator_payment_paymentMakingCard_proto_rawDesc)))
	})
	return file_paymentSimulator_payment_paymentMakingCard_proto_rawDescData
}

var file_paymentSimulator_payment_paymentMakingCard_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_paymentSimulator_payment_paymentMakingCard_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_paymentSimulator_payment_paymentMakingCard_proto_goTypes = []any{
	(PaymentStatus)(0),            // 0: paymentSimulator.payment.v1.PaymentStatus
	(*PayWithCardRequest)(nil),    // 1: paymentSimulator.payment.v1.PayWithCardRequest
	(*Card)(nil),                  // 2: paymentSimulator.payment.v1.Card
	(*PayWithCardResponse)(nil),   // 3: paymentSimulator.payment.v1.PayWithCardResponse
	(*CardSummary)(nil),           // 4: paymentSimulator.common.CardSummary
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_paymentSimulator_payment_paymentMakingCard_proto_depIdxs = []int32{
	2, // 0: paymentSimulator.payment.v1.PayWithCardRequest.card:type_name -> paymentSimulator.payment.v1.Card
	0, // 1: paymentSimulator.payment.v1.PayWithCardResponse.status:type_name -> paymentSimulator.payment.v1.PaymentStatus
	4, // 2: paymentSimulator.payment.v1.PayWithCardResponse.card:type_name -> paymentSimulator.common.CardSummary
	5, // 3: paymentSimulator.payment.v1.PayWithCardResponse.processed_at:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_paymentSimulator_payment_paymentMakingCard_proto_init() }
func file_paymentSimulator_payment_paymentMakingCard_proto_init() {
	if File_paymentSimulator_payment_paymentMakingCard_proto != nil {
		return
	}
	file_paymentSimulator_common_cardSummary_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_paymentSimulator_payment_paymentMakingCard_proto_rawDesc), len(file_paymentSimulator_payment_paymentMakingCard_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_paymentSimulator_payment_paymentMakingCard_proto_goTypes,
		DependencyIndexes: file_paymentSimulator_payment_paymentMakingCard_proto_depIdxs,
		EnumInfos:         file_paymentSimulator_payment_paymentMakingCard_proto_enumTypes,
		MessageInfos:      file_paymentSimulator_payment_paymentMakingCard_proto_msgTypes,
	}.Build()
	File_paymentSimulator_payment_paymentMakingCard_proto = out.File
	file_paymentSimulator_payment_paymentMakingCard_proto_goTypes = nil
	file_paymentSimulator_payment_paymentMakingCard_proto_depIdxs = nil
}
