// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: paymentSimulator/common/paymentMethod.proto

package dto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentMethod int32

const (
	PaymentMethod_PAYMENT_METHOD_UNSPECIFIED PaymentMethod = 0
	PaymentMethod_PAYMENT_METHOD_CREDIT_CARD PaymentMethod = 1
)

// Enum value maps for PaymentMethod.
var (
	PaymentMethod_name = map[int32]string{
		0: "PAYMENT_METHOD_UNSPECIFIED",
		1: "PAYMENT_METHOD_CREDIT_CARD",
	}
	PaymentMethod_value = map[string]int32{
		"PAYMENT_METHOD_UNSPECIFIED": 0,
		"PAYMENT_METHOD_CREDIT_CARD": 1,
	}
)

func (x PaymentMethod) Enum() *PaymentMethod {
	p := new(PaymentMethod)
	*p = x
	return p
}

func (x PaymentMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_paymentSimulator_common_paymentMethod_proto_enumTypes[0].Descriptor()
}

func (PaymentMethod) Type() protoreflect.EnumType {
	return &file_paymentSimulator_common_paymentMethod_proto_enumTypes[0]
}

func (x PaymentMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentMethod.Descriptor instead.
func (PaymentMethod) EnumDescriptor() ([]byte, []int) {
	return file_paymentSimulator_common_paymentMethod_proto_rawDescGZIP(), []int{0}
}

var File_paymentSimulator_common_paymentMethod_proto protoreflect.FileDescriptor

const file_paymentSimulator_common_paymentMethod_proto_rawDesc = "" +
	"\n" +
	"+paymentSimulator/common/paymentMethod.proto\x12\x17paymentSimulator.common*O\n" +
	"\rPaymentMethod\x12\x1e\n" +
	"\x1aPAYMENT_METHOD_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aPAYMENT_METHOD_CREDIT_CARD\x10\x01B@Z>github.com/Kenji-Uema/paymentSimulator/internal/domain/dto;dtob\x06proto3"

var (
	file_paymentSimulator_common_paymentMethod_proto_rawDescOnce sync.Once
	file_paymentSimulator_common_paymentMethod_proto_rawDescData []byte
)

func file_paymentSimulator_common_paymentMethod_proto_rawDescGZIP() []byte {
	file_paymentSimulator_common_paymentMethod_proto_rawDescOnce.Do(func() {
		file_paymentSimulator_common_paymentMethod_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_paymentSimulator_common_paymentMethod_proto_rawDesc), len(file_paymentSimulator_common_paymentMethod_proto_rawDesc)))
	})
	return file_paymentSimulator_common_paymentMethod_proto_rawDescData
}

var file_paymentSimulator_common_paymentMethod_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_paymentSimulator_common_paymentMethod_proto_goTypes = []any{
	(PaymentMethod)(0), // 0: paymentSimulator.common.PaymentMethod
}
var file_paymentSimulator_common_paymentMethod_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_paymentSimulator_common_paymentMethod_proto_init() }
func file_paymentSimulator_common_paymentMethod_proto_init() {
	if File_paymentSimulator_common_paymentMethod_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_paymentSimulator_common_paymentMethod_proto_rawDesc), len(file_paymentSimulator_common_paymentMethod_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_paymentSimulator_common_paymentMethod_proto_goTypes,
		DependencyIndexes: file_paymentSimulator_common_paymentMethod_proto_depIdxs,
		EnumInfos:         file_paymentSimulator_common_paymentMethod_proto_enumTypes,
	}.Build()
	File_paymentSimulator_common_paymentMethod_proto = out.File
	file_paymentSimulator_common_paymentMethod_proto_goTypes = nil
	file_paymentSimulator_common_paymentMethod_proto_depIdxs = nil
}
