// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: paymentSimulator/payment/paymentMakingCard.proto

package dto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FailureCode int32

const (
	FailureCode_FAILURE_CODE_UNSPECIFIED        FailureCode = 0
	FailureCode_FAILURE_CODE_CARD_DECLINED      FailureCode = 1
	FailureCode_FAILURE_CODE_INVALID_CARD       FailureCode = 2
	FailureCode_FAILURE_CODE_EXPIRED_CARD       FailureCode = 3
	FailureCode_FAILURE_CODE_INSUFFICIENT_FUNDS FailureCode = 4
	FailureCode_FAILURE_CODE_PROCESSING_ERROR   FailureCode = 5
	FailureCode_FAILURE_CODE_SESSION_EXPIRED    FailureCode = 6
	FailureCode_FAILURE_CODE_ALREADY_PAID       FailureCode = 7
	FailureCode_FAILURE_CODE_CANCELLED          FailureCode = 8
)

// Enum value maps for FailureCode.
var (
	FailureCode_name = map[int32]string{
		0: "FAILURE_CODE_UNSPECIFIED",
		1: "FAILURE_CODE_CARD_DECLINED",
		2: "FAILURE_CODE_INVALID_CARD",
		3: "FAILURE_CODE_EXPIRED_CARD",
		4: "FAILURE_CODE_INSUFFICIENT_FUNDS",
		5: "FAILURE_CODE_PROCESSING_ERROR",
		6: "FAILURE_CODE_SESSION_EXPIRED",
		7: "FAILURE_CODE_ALREADY_PAID",
		8: "FAILURE_CODE_CANCELLED",
	}
	FailureCode_value = map[string]int32{
		"FAILURE_CODE_UNSPECIFIED":        0,
		"FAILURE_CODE_CARD_DECLINED":      1,
		"FAILURE_CODE_INVALID_CARD":       2,
		"FAILURE_CODE_EXPIRED_CARD":       3,
		"FAILURE_CODE_INSUFFICIENT_FUNDS": 4,
		"FAILURE_CODE_PROCESSING_ERROR":   5,
		"FAILURE_CODE_SESSION_EXPIRED":    6,
		"FAILURE_CODE_ALREADY_PAID":       7,
		"FAILURE_CODE_CANCELLED":          8,
	}
)

func (x FailureCode) Enum() *FailureCode {
	p := new(FailureCode)
	*p = x
	return p
}

func (x FailureCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FailureCode) Descriptor() protoreflect.EnumDescriptor {
	return file_paymentSimulator_payment_paymentMakingCard_proto_enumTypes[0].Descriptor()
}

func (FailureCode) Type() protoreflect.EnumType {
	return &file_paymentSimulator_payment_paymentMakingCard_proto_enumTypes[0]
}

func (x FailureCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FailureCode.Descriptor instead.
func (FailureCode) EnumDescriptor() ([]byte, []int) {
	return file_paymentSimulator_payment_paymentMakingCard_proto_rawDescGZIP(), []int{0}
}

type PaymentStatus int32

const (
	PaymentStatus_PAYMENT_STATUS_UNSPECIFIED PaymentStatus = 0
	PaymentStatus_PAYMENT_STATUS_PENDING     PaymentStatus = 1
	PaymentStatus_PAYMENT_STATUS_SUCCEEDED   PaymentStatus = 2
	PaymentStatus_PAYMENT_STATUS_FAILED      PaymentStatus = 3
	PaymentStatus_PAYMENT_STATUS_EXPIRED     PaymentStatus = 4
	PaymentStatus_PAYMENT_STATUS_CANCELLED   PaymentStatus = 5
)

// Enum value maps for PaymentStatus.
var (
	PaymentStatus_name = map[int32]string{
		0: "PAYMENT_STATUS_UNSPECIFIED",
		1: "PAYMENT_STATUS_PENDING",
		2: "PAYMENT_STATUS_SUCCEEDED",
		3: "PAYMENT_STATUS_FAILED",
		4: "PAYMENT_STATUS_EXPIRED",
		5: "PAYMENT_STATUS_CANCELLED",
	}
	PaymentStatus_value = map[string]int32{
		"PAYMENT_STATUS_UNSPECIFIED": 0,
		"PAYMENT_STATUS_PENDING":     1,
		"PAYMENT_STATUS_SUCCEEDED":   2,
		"PAYMENT_STATUS_FAILED":      3,
		"PAYMENT_STATUS_EXPIRED":     4,
		"PAYMENT_STATUS_CANCELLED":   5,
	}
)

func (x PaymentStatus) Enum() *PaymentStatus {
	p := new(PaymentStatus)
	*p = x
	return p
}

func (x PaymentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_paymentSimulator_payment_paymentMakingCard_proto_enumTypes[1].Descriptor()
}

func (PaymentStatus) Type() protoreflect.EnumType {
	return &file_paymentSimulator_payment_paymentMakingCard_proto_enumTypes[1]
}

func (x PaymentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentStatus.Descriptor instead.
func (PaymentStatus) EnumDescriptor() ([]byte, []int) {
	return file_paymentSimulator_payment_paymentMakingCard_proto_rawDescGZIP(), []int{1}
}

// request
type PayWithCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Card          *CardInput             `protobuf:"bytes,1,opt,name=card,proto3" json:"card,omitempty"`
	InvoiceId     string                 `protobuf:"bytes,2,opt,name=invoice_id,json=invoiceId,proto3" json:"invoice_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayWithCardRequest) Reset() {
	*x = PayWithCardRequest{}
	mi := &file_paymentSimulator_payment_paymentMakingCard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayWithCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayWithCardRequest) ProtoMessage() {}

func (x *PayWithCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paymentSimulator_payment_paymentMakingCard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayWithCardRequest.ProtoReflect.Descriptor instead.
func (*PayWithCardRequest) Descriptor() ([]byte, []int) {
	return file_paymentSimulator_payment_paymentMakingCard_proto_rawDescGZIP(), []int{0}
}

func (x *PayWithCardRequest) GetCard() *CardInput {
	if x != nil {
		return x.Card
	}
	return nil
}

func (x *PayWithCardRequest) GetInvoiceId() string {
	if x != nil {
		return x.InvoiceId
	}
	return ""
}

type CardInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Brand         string                 `protobuf:"bytes,1,opt,name=brand,proto3" json:"brand,omitempty"`
	Number        string                 `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
	ExpMonth      uint32                 `protobuf:"varint,3,opt,name=exp_month,json=expMonth,proto3" json:"exp_month,omitempty"`
	ExpYear       uint32                 `protobuf:"varint,4,opt,name=exp_year,json=expYear,proto3" json:"exp_year,omitempty"`
	Cvv           string                 `protobuf:"bytes,5,opt,name=cvv,proto3" json:"cvv,omitempty"`
	HolderName    string                 `protobuf:"bytes,6,opt,name=holder_name,json=holderName,proto3" json:"holder_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardInput) Reset() {
	*x = CardInput{}
	mi := &file_paymentSimulator_payment_paymentMakingCard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardInput) ProtoMessage() {}

func (x *CardInput) ProtoReflect() protoreflect.Message {
	mi := &file_paymentSimulator_payment_paymentMakingCard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardInput.ProtoReflect.Descriptor instead.
func (*CardInput) Descriptor() ([]byte, []int) {
	return file_paymentSimulator_payment_paymentMakingCard_proto_rawDescGZIP(), []int{1}
}

func (x *CardInput) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *CardInput) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *CardInput) GetExpMonth() uint32 {
	if x != nil {
		return x.ExpMonth
	}
	return 0
}

func (x *CardInput) GetExpYear() uint32 {
	if x != nil {
		return x.ExpYear
	}
	return 0
}

func (x *CardInput) GetCvv() string {
	if x != nil {
		return x.Cvv
	}
	return ""
}

func (x *CardInput) GetHolderName() string {
	if x != nil {
		return x.HolderName
	}
	return ""
}

// response
type PayWithCardResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PaymentIntentId string                 `protobuf:"bytes,1,opt,name=payment_intent_id,json=paymentIntentId,proto3" json:"payment_intent_id,omitempty"`
	Status          PaymentStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=paymentSimulator.payment.v1.PaymentStatus" json:"status,omitempty"`
	ReceiptId       string                 `protobuf:"bytes,3,opt,name=receipt_id,json=receiptId,proto3" json:"receipt_id,omitempty"`
	ProcessedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=processed_at,json=processedAt,proto3" json:"processed_at,omitempty"`
	Failure         *Failure               `protobuf:"bytes,5,opt,name=failure,proto3" json:"failure,omitempty"`
	Card            *CardSummary           `protobuf:"bytes,6,opt,name=card,proto3" json:"card,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PayWithCardResponse) Reset() {
	*x = PayWithCardResponse{}
	mi := &file_paymentSimulator_payment_paymentMakingCard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayWithCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayWithCardResponse) ProtoMessage() {}

func (x *PayWithCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paymentSimulator_payment_paymentMakingCard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayWithCardResponse.ProtoReflect.Descriptor instead.
func (*PayWithCardResponse) Descriptor() ([]byte, []int) {
	return file_paymentSimulator_payment_paymentMakingCard_proto_rawDescGZIP(), []int{2}
}

func (x *PayWithCardResponse) GetPaymentIntentId() string {
	if x != nil {
		return x.PaymentIntentId
	}
	return ""
}

func (x *PayWithCardResponse) GetStatus() PaymentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentStatus_PAYMENT_STATUS_UNSPECIFIED
}

func (x *PayWithCardResponse) GetReceiptId() string {
	if x != nil {
		return x.ReceiptId
	}
	return ""
}

func (x *PayWithCardResponse) GetProcessedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ProcessedAt
	}
	return nil
}

func (x *PayWithCardResponse) GetFailure() *Failure {
	if x != nil {
		return x.Failure
	}
	return nil
}

func (x *PayWithCardResponse) GetCard() *CardSummary {
	if x != nil {
		return x.Card
	}
	return nil
}

type Failure struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          FailureCode            `protobuf:"varint,1,opt,name=code,proto3,enum=paymentSimulator.payment.v1.FailureCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Failure) Reset() {
	*x = Failure{}
	mi := &file_paymentSimulator_payment_paymentMakingCard_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Failure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Failure) ProtoMessage() {}

func (x *Failure) ProtoReflect() protoreflect.Message {
	mi := &file_paymentSimulator_payment_paymentMakingCard_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Failure.ProtoReflect.Descriptor instead.
func (*Failure) Descriptor() ([]byte, []int) {
	return file_paymentSimulator_payment_paymentMakingCard_proto_rawDescGZIP(), []int{3}
}

func (x *Failure) GetCode() FailureCode {
	if x != nil {
		return x.Code
	}
	return FailureCode_FAILURE_CODE_UNSPECIFIED
}

func (x *Failure) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_paymentSimulator_payment_paymentMakingCard_proto protoreflect.FileDescriptor

const file_paymentSimulator_payment_paymentMakingCard_proto_rawDesc = "" +
	"\n" +
	"0paymentSimulator/payment/paymentMakingCard.proto\x12\x1bpaymentSimulator.payment.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a)paymentSimulator/common/cardSummary.proto\"o\n" +
	"\x12PayWithCardRequest\x12:\n" +
	"\x04card\x18\x01 \x01(\v2&.paymentSimulator.payment.v1.CardInputR\x04card\x12\x1d\n" +
	"\n" +
	"invoice_id\x18\x02 \x01(\tR\tinvoiceId\"\xa4\x01\n" +
	"\tCardInput\x12\x14\n" +
	"\x05brand\x18\x01 \x01(\tR\x05brand\x12\x16\n" +
	"\x06number\x18\x02 \x01(\tR\x06number\x12\x1b\n" +
	"\texp_month\x18\x03 \x01(\rR\bexpMonth\x12\x19\n" +
	"\bexp_year\x18\x04 \x01(\rR\aexpYear\x12\x10\n" +
	"\x03cvv\x18\x05 \x01(\tR\x03cvv\x12\x1f\n" +
	"\vholder_name\x18\x06 \x01(\tR\n" +
	"holderName\"\xdd\x02\n" +
	"\x13PayWithCardResponse\x12*\n" +
	"\x11payment_intent_id\x18\x01 \x01(\tR\x0fpaymentIntentId\x12B\n" +
	"\x06status\x18\x02 \x01(\x0e2*.paymentSimulator.payment.v1.PaymentStatusR\x06status\x12\x1d\n" +
	"\n" +
	"receipt_id\x18\x03 \x01(\tR\treceiptId\x12=\n" +
	"\fprocessed_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vprocessedAt\x12>\n" +
	"\afailure\x18\x05 \x01(\v2$.paymentSimulator.payment.v1.FailureR\afailure\x128\n" +
	"\x04card\x18\x06 \x01(\v2$.paymentSimulator.common.CardSummaryR\x04card\"a\n" +
	"\aFailure\x12<\n" +
	"\x04code\x18\x01 \x01(\x0e2(.paymentSimulator.payment.v1.FailureCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*\xae\x02\n" +
	"\vFailureCode\x12\x1c\n" +
	"\x18FAILURE_CODE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aFAILURE_CODE_CARD_DECLINED\x10\x01\x12\x1d\n" +
	"\x19FAILURE_CODE_INVALID_CARD\x10\x02\x12\x1d\n" +
	"\x19FAILURE_CODE_EXPIRED_CARD\x10\x03\x12#\n" +
	"\x1fFAILURE_CODE_INSUFFICIENT_FUNDS\x10\x04\x12!\n" +
	"\x1dFAILURE_CODE_PROCESSING_ERROR\x10\x05\x12 \n" +
	"\x1cFAILURE_CODE_SESSION_EXPIRED\x10\x06\x12\x1d\n" +
	"\x19FAILURE_CODE_ALREADY_PAID\x10\a\x12\x1a\n" +
	"\x16FAILURE_CODE_CANCELLED\x10\b*\xbe\x01\n" +
	"\rPaymentStatus\x12\x1e\n" +
	"\x1aPAYMENT_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16PAYMENT_STATUS_PENDING\x10\x01\x12\x1c\n" +
	"\x18PAYMENT_STATUS_SUCCEEDED\x10\x02\x12\x19\n" +
	"\x15PAYMENT_STATUS_FAILED\x10\x03\x12\x1a\n" +
	"\x16PAYMENT_STATUS_EXPIRED\x10\x04\x12\x1c\n" +
	"\x18PAYMENT_STATUS_CANCELLED\x10\x05B@Z>github.com/Kenji-Uema/paymentSimulator/internal/domain/dto;dtob\x06proto3"

var (
	file_paymentSimulator_payment_paymentMakingCard_proto_rawDescOnce sync.Once
	file_paymentSimulator_payment_paymentMakingCard_proto_rawDescData []byte
)

func file_paymentSimulator_payment_paymentMakingCard_proto_rawDescGZIP() []byte {
	file_paymentSimulator_payment_paymentMakingCard_proto_rawDescOnce.Do(func() {
		file_paymentSimulator_payment_paymentMakingCard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_paymentSimulator_payment_paymentMakingCard_proto_rawDesc), len(file_paymentSimulator_payment_paymentMakingCard_proto_rawDesc)))
	})
	return file_paymentSimulator_payment_paymentMakingCard_proto_rawDescData
}

var file_paymentSimulator_payment_paymentMakingCard_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_paymentSimulator_payment_paymentMakingCard_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_paymentSimulator_payment_paymentMakingCard_proto_goTypes = []any{
	(FailureCode)(0),              // 0: paymentSimulator.payment.v1.FailureCode
	(PaymentStatus)(0),            // 1: paymentSimulator.payment.v1.PaymentStatus
	(*PayWithCardRequest)(nil),    // 2: paymentSimulator.payment.v1.PayWithCardRequest
	(*CardInput)(nil),             // 3: paymentSimulator.payment.v1.CardInput
	(*PayWithCardResponse)(nil),   // 4: paymentSimulator.payment.v1.PayWithCardResponse
	(*Failure)(nil),               // 5: paymentSimulator.payment.v1.Failure
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
	(*CardSummary)(nil),           // 7: paymentSimulator.common.CardSummary
}
var file_paymentSimulator_payment_paymentMakingCard_proto_depIdxs = []int32{
	3, // 0: paymentSimulator.payment.v1.PayWithCardRequest.card:type_name -> paymentSimulator.payment.v1.CardInput
	1, // 1: paymentSimulator.payment.v1.PayWithCardResponse.status:type_name -> paymentSimulator.payment.v1.PaymentStatus
	6, // 2: paymentSimulator.payment.v1.PayWithCardResponse.processed_at:type_name -> google.protobuf.Timestamp
	5, // 3: paymentSimulator.payment.v1.PayWithCardResponse.failure:type_name -> paymentSimulator.payment.v1.Failure
	7, // 4: paymentSimulator.payment.v1.PayWithCardResponse.card:type_name -> paymentSimulator.common.CardSummary
	0, // 5: paymentSimulator.payment.v1.Failure.code:type_name -> paymentSimulator.payment.v1.FailureCode
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_paymentSimulator_payment_paymentMakingCard_proto_init() }
func file_paymentSimulator_payment_paymentMakingCard_proto_init() {
	if File_paymentSimulator_payment_paymentMakingCard_proto != nil {
		return
	}
	file_paymentSimulator_common_cardSummary_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_paymentSimulator_payment_paymentMakingCard_proto_rawDesc), len(file_paymentSimulator_payment_paymentMakingCard_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_paymentSimulator_payment_paymentMakingCard_proto_goTypes,
		DependencyIndexes: file_paymentSimulator_payment_paymentMakingCard_proto_depIdxs,
		EnumInfos:         file_paymentSimulator_payment_paymentMakingCard_proto_enumTypes,
		MessageInfos:      file_paymentSimulator_payment_paymentMakingCard_proto_msgTypes,
	}.Build()
	File_paymentSimulator_payment_paymentMakingCard_proto = out.File
	file_paymentSimulator_payment_paymentMakingCard_proto_goTypes = nil
	file_paymentSimulator_payment_paymentMakingCard_proto_depIdxs = nil
}
