// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: paymentSimulator/payment/paymentConfirmation.proto

package dto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentConfirmation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BookingId     string                 `protobuf:"bytes,2,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	PayerId       string                 `protobuf:"bytes,3,opt,name=payer_id,json=payerId,proto3" json:"payer_id,omitempty"`
	InvoiceNumber string                 `protobuf:"bytes,4,opt,name=invoice_number,json=invoiceNumber,proto3" json:"invoice_number,omitempty"`
	ReceiptNumber string                 `protobuf:"bytes,5,opt,name=receipt_number,json=receiptNumber,proto3" json:"receipt_number,omitempty"`
	ConfirmedAt   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=confirmed_at,json=confirmedAt,proto3" json:"confirmed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentConfirmation) Reset() {
	*x = PaymentConfirmation{}
	mi := &file_paymentSimulator_payment_paymentConfirmation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentConfirmation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentConfirmation) ProtoMessage() {}

func (x *PaymentConfirmation) ProtoReflect() protoreflect.Message {
	mi := &file_paymentSimulator_payment_paymentConfirmation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentConfirmation.ProtoReflect.Descriptor instead.
func (*PaymentConfirmation) Descriptor() ([]byte, []int) {
	return file_paymentSimulator_payment_paymentConfirmation_proto_rawDescGZIP(), []int{0}
}

func (x *PaymentConfirmation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PaymentConfirmation) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *PaymentConfirmation) GetPayerId() string {
	if x != nil {
		return x.PayerId
	}
	return ""
}

func (x *PaymentConfirmation) GetInvoiceNumber() string {
	if x != nil {
		return x.InvoiceNumber
	}
	return ""
}

func (x *PaymentConfirmation) GetReceiptNumber() string {
	if x != nil {
		return x.ReceiptNumber
	}
	return ""
}

func (x *PaymentConfirmation) GetConfirmedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ConfirmedAt
	}
	return nil
}

var File_paymentSimulator_payment_paymentConfirmation_proto protoreflect.FileDescriptor

const file_paymentSimulator_payment_paymentConfirmation_proto_rawDesc = "" +
	"\n" +
	"2paymentSimulator/payment/paymentConfirmation.proto\x12\x1bpaymentSimulator.payment.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a#paymentSimulator/common/money.proto\x1a+paymentSimulator/common/paymentMethod.proto\x1a)paymentSimulator/common/cardSummary.proto\"\xec\x01\n" +
	"\x13PaymentConfirmation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x02 \x01(\tR\tbookingId\x12\x19\n" +
	"\bpayer_id\x18\x03 \x01(\tR\apayerId\x12%\n" +
	"\x0einvoice_number\x18\x04 \x01(\tR\rinvoiceNumber\x12%\n" +
	"\x0ereceipt_number\x18\x05 \x01(\tR\rreceiptNumber\x12=\n" +
	"\fconfirmed_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vconfirmedAtB@Z>github.com/Kenji-Uema/paymentSimulator/internal/domain/dto;dtob\x06proto3"

var (
	file_paymentSimulator_payment_paymentConfirmation_proto_rawDescOnce sync.Once
	file_paymentSimulator_payment_paymentConfirmation_proto_rawDescData []byte
)

func file_paymentSimulator_payment_paymentConfirmation_proto_rawDescGZIP() []byte {
	file_paymentSimulator_payment_paymentConfirmation_proto_rawDescOnce.Do(func() {
		file_paymentSimulator_payment_paymentConfirmation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_paymentSimulator_payment_paymentConfirmation_proto_rawDesc), len(file_paymentSimulator_payment_paymentConfirmation_proto_rawDesc)))
	})
	return file_paymentSimulator_payment_paymentConfirmation_proto_rawDescData
}

var file_paymentSimulator_payment_paymentConfirmation_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_paymentSimulator_payment_paymentConfirmation_proto_goTypes = []any{
	(*PaymentConfirmation)(nil),   // 0: paymentSimulator.payment.v1.PaymentConfirmation
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_paymentSimulator_payment_paymentConfirmation_proto_depIdxs = []int32{
	1, // 0: paymentSimulator.payment.v1.PaymentConfirmation.confirmed_at:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_paymentSimulator_payment_paymentConfirmation_proto_init() }
func file_paymentSimulator_payment_paymentConfirmation_proto_init() {
	if File_paymentSimulator_payment_paymentConfirmation_proto != nil {
		return
	}
	file_paymentSimulator_common_money_proto_init()
	file_paymentSimulator_common_paymentMethod_proto_init()
	file_paymentSimulator_common_cardSummary_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_paymentSimulator_payment_paymentConfirmation_proto_rawDesc), len(file_paymentSimulator_payment_paymentConfirmation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_paymentSimulator_payment_paymentConfirmation_proto_goTypes,
		DependencyIndexes: file_paymentSimulator_payment_paymentConfirmation_proto_depIdxs,
		MessageInfos:      file_paymentSimulator_payment_paymentConfirmation_proto_msgTypes,
	}.Build()
	File_paymentSimulator_payment_paymentConfirmation_proto = out.File
	file_paymentSimulator_payment_paymentConfirmation_proto_goTypes = nil
	file_paymentSimulator_payment_paymentConfirmation_proto_depIdxs = nil
}
