// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: paymentSimulator/payment/service/paymentMakingService.proto

package payment

import (
	dto "github.com/Kenji-Uema/paymentSimulator/internal/domain/dto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_paymentSimulator_payment_service_paymentMakingService_proto protoreflect.FileDescriptor

const file_paymentSimulator_payment_service_paymentMakingService_proto_rawDesc = "" +
	"\n" +
	";paymentSimulator/payment/service/paymentMakingService.proto\x12\x1bpaymentSimulator.payment.v1\x1a\x1cgoogle/api/annotations.proto\x1a*paymentSimulator/payment/payWithCard.proto2\xbe\x01\n" +
	"\x14PaymentMakingService\x12\xa5\x01\n" +
	"\vPayWithCard\x12/.paymentSimulator.payment.v1.PayWithCardRequest\x1a0.paymentSimulator.payment.v1.PayWithCardResponse\"3\x82\xd3\xe4\x93\x02-:\x04card\"%/v1/payments/invoice/{invoice_number}BEZCgithub.com/Kenji-Uema/paymentSimulator/internal/app/payment;paymentb\x06proto3"

var file_paymentSimulator_payment_service_paymentMakingService_proto_goTypes = []any{
	(*dto.PayWithCardRequest)(nil),  // 0: paymentSimulator.payment.v1.PayWithCardRequest
	(*dto.PayWithCardResponse)(nil), // 1: paymentSimulator.payment.v1.PayWithCardResponse
}
var file_paymentSimulator_payment_service_paymentMakingService_proto_depIdxs = []int32{
	0, // 0: paymentSimulator.payment.v1.PaymentMakingService.PayWithCard:input_type -> paymentSimulator.payment.v1.PayWithCardRequest
	1, // 1: paymentSimulator.payment.v1.PaymentMakingService.PayWithCard:output_type -> paymentSimulator.payment.v1.PayWithCardResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_paymentSimulator_payment_service_paymentMakingService_proto_init() }
func file_paymentSimulator_payment_service_paymentMakingService_proto_init() {
	if File_paymentSimulator_payment_service_paymentMakingService_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_paymentSimulator_payment_service_paymentMakingService_proto_rawDesc), len(file_paymentSimulator_payment_service_paymentMakingService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_paymentSimulator_payment_service_paymentMakingService_proto_goTypes,
		DependencyIndexes: file_paymentSimulator_payment_service_paymentMakingService_proto_depIdxs,
	}.Build()
	File_paymentSimulator_payment_service_paymentMakingService_proto = out.File
	file_paymentSimulator_payment_service_paymentMakingService_proto_goTypes = nil
	file_paymentSimulator_payment_service_paymentMakingService_proto_depIdxs = nil
}
