// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: clockEmu/now.proto

package clock

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NowResponse) Reset() {
	*x = NowResponse{}
	mi := &file_clockEmu_now_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NowResponse) ProtoMessage() {}

func (x *NowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clockEmu_now_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NowResponse.ProtoReflect.Descriptor instead.
func (*NowResponse) Descriptor() ([]byte, []int) {
	return file_clockEmu_now_proto_rawDescGZIP(), []int{0}
}

func (x *NowResponse) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

var File_clockEmu_now_proto protoreflect.FileDescriptor

const file_clockEmu_now_proto_rawDesc = "" +
	"\n" +
	"\x12clockEmu/now.proto\x12\rclockEmulator\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"=\n" +
	"\vNowResponse\x12.\n" +
	"\x04time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04time2I\n" +
	"\fClockService\x129\n" +
	"\x03Now\x12\x16.google.protobuf.Empty\x1a\x1a.clockEmulator.NowResponseBLZJgithub.com/Kenji-Uema/paymentSimulator/internal/transport/grpc/clock;clockb\x06proto3"

var (
	file_clockEmu_now_proto_rawDescOnce sync.Once
	file_clockEmu_now_proto_rawDescData []byte
)

func file_clockEmu_now_proto_rawDescGZIP() []byte {
	file_clockEmu_now_proto_rawDescOnce.Do(func() {
		file_clockEmu_now_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clockEmu_now_proto_rawDesc), len(file_clockEmu_now_proto_rawDesc)))
	})
	return file_clockEmu_now_proto_rawDescData
}

var file_clockEmu_now_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_clockEmu_now_proto_goTypes = []any{
	(*NowResponse)(nil),           // 0: clockEmulator.NowResponse
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 2: google.protobuf.Empty
}
var file_clockEmu_now_proto_depIdxs = []int32{
	1, // 0: clockEmulator.NowResponse.time:type_name -> google.protobuf.Timestamp
	2, // 1: clockEmulator.ClockService.Now:input_type -> google.protobuf.Empty
	0, // 2: clockEmulator.ClockService.Now:output_type -> clockEmulator.NowResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_clockEmu_now_proto_init() }
func file_clockEmu_now_proto_init() {
	if File_clockEmu_now_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clockEmu_now_proto_rawDesc), len(file_clockEmu_now_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_clockEmu_now_proto_goTypes,
		DependencyIndexes: file_clockEmu_now_proto_depIdxs,
		MessageInfos:      file_clockEmu_now_proto_msgTypes,
	}.Build()
	File_clockEmu_now_proto = out.File
	file_clockEmu_now_proto_goTypes = nil
	file_clockEmu_now_proto_depIdxs = nil
}
