// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: paymentSimulator/payment/service/paymentRequestReissueService.proto

package payment

import (
	context "context"
	dto "github.com/Kenji-Uema/paymentSimulator/internal/domain/dto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PaymentReissueService_Reissue_FullMethodName = "/paymentSimulator.payment.v1.PaymentReissueService/Reissue"
)

// PaymentReissueServiceClient is the client API for PaymentReissueService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaymentReissueServiceClient interface {
	Reissue(ctx context.Context, in *dto.ReissuePaymentRequest, opts ...grpc.CallOption) (*dto.PaymentRequest, error)
}

type paymentReissueServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentReissueServiceClient(cc grpc.ClientConnInterface) PaymentReissueServiceClient {
	return &paymentReissueServiceClient{cc}
}

func (c *paymentReissueServiceClient) Reissue(ctx context.Context, in *dto.ReissuePaymentRequest, opts ...grpc.CallOption) (*dto.PaymentRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(dto.PaymentRequest)
	err := c.cc.Invoke(ctx, PaymentReissueService_Reissue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentReissueServiceServer is the server API for PaymentReissueService service.
// All implementations must embed UnimplementedPaymentReissueServiceServer
// for forward compatibility.
type PaymentReissueServiceServer interface {
	Reissue(context.Context, *dto.ReissuePaymentRequest) (*dto.PaymentRequest, error)
	mustEmbedUnimplementedPaymentReissueServiceServer()
}

// UnimplementedPaymentReissueServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaymentReissueServiceServer struct{}

func (UnimplementedPaymentReissueServiceServer) Reissue(context.Context, *dto.ReissuePaymentRequest) (*dto.PaymentRequest, error) {
	return nil, status.Error(codes.Unimplemented, "method Reissue not implemented")
}
func (UnimplementedPaymentReissueServiceServer) mustEmbedUnimplementedPaymentReissueServiceServer() {}
func (UnimplementedPaymentReissueServiceServer) testEmbeddedByValue()                               {}

// UnsafePaymentReissueServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentReissueServiceServer will
// result in compilation errors.
type UnsafePaymentReissueServiceServer interface {
	mustEmbedUnimplementedPaymentReissueServiceServer()
}

func RegisterPaymentReissueServiceServer(s grpc.ServiceRegistrar, srv PaymentReissueServiceServer) {
	// If the following call panics, it indicates UnimplementedPaymentReissueServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PaymentReissueService_ServiceDesc, srv)
}

func _PaymentReissueService_Reissue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dto.ReissuePaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentReissueServiceServer).Reissue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentReissueService_Reissue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentReissueServiceServer).Reissue(ctx, req.(*dto.ReissuePaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PaymentReissueService_ServiceDesc is the grpc.ServiceDesc for PaymentReissueService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaymentReissueService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "paymentSimulator.payment.v1.PaymentReissueService",
	HandlerType: (*PaymentReissueServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Reissue",
			Handler:    _PaymentReissueService_Reissue_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "paymentSimulator/payment/service/paymentRequestReissueService.proto",
}
