// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: paymentSimulator/payment/service/paymentRequestReissueService.proto

package payment

import (
	context "context"
	dto "github.com/Kenji-Uema/paymentSimulator/internal/domain/dto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PaymentRequestService_Reissue_FullMethodName = "/paymentSimulator.payment.v1.PaymentRequestService/Reissue"
)

// PaymentRequestServiceClient is the client API for PaymentRequestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaymentRequestServiceClient interface {
	Reissue(ctx context.Context, in *dto.ReissuePaymentRequest, opts ...grpc.CallOption) (*dto.PaymentRequest, error)
}

type paymentRequestServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentRequestServiceClient(cc grpc.ClientConnInterface) PaymentRequestServiceClient {
	return &paymentRequestServiceClient{cc}
}

func (c *paymentRequestServiceClient) Reissue(ctx context.Context, in *dto.ReissuePaymentRequest, opts ...grpc.CallOption) (*dto.PaymentRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(dto.PaymentRequest)
	err := c.cc.Invoke(ctx, PaymentRequestService_Reissue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentRequestServiceServer is the server API for PaymentRequestService service.
// All implementations must embed UnimplementedPaymentRequestServiceServer
// for forward compatibility.
type PaymentRequestServiceServer interface {
	Reissue(context.Context, *dto.ReissuePaymentRequest) (*dto.PaymentRequest, error)
	mustEmbedUnimplementedPaymentRequestServiceServer()
}

// UnimplementedPaymentRequestServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaymentRequestServiceServer struct{}

func (UnimplementedPaymentRequestServiceServer) Reissue(context.Context, *dto.ReissuePaymentRequest) (*dto.PaymentRequest, error) {
	return nil, status.Error(codes.Unimplemented, "method Reissue not implemented")
}
func (UnimplementedPaymentRequestServiceServer) mustEmbedUnimplementedPaymentRequestServiceServer() {}
func (UnimplementedPaymentRequestServiceServer) testEmbeddedByValue()                               {}

// UnsafePaymentRequestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentRequestServiceServer will
// result in compilation errors.
type UnsafePaymentRequestServiceServer interface {
	mustEmbedUnimplementedPaymentRequestServiceServer()
}

func RegisterPaymentRequestServiceServer(s grpc.ServiceRegistrar, srv PaymentRequestServiceServer) {
	// If the following call panics, it indicates UnimplementedPaymentRequestServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PaymentRequestService_ServiceDesc, srv)
}

func _PaymentRequestService_Reissue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dto.ReissuePaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentRequestServiceServer).Reissue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentRequestService_Reissue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentRequestServiceServer).Reissue(ctx, req.(*dto.ReissuePaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PaymentRequestService_ServiceDesc is the grpc.ServiceDesc for PaymentRequestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaymentRequestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "paymentSimulator.payment.v1.PaymentRequestService",
	HandlerType: (*PaymentRequestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Reissue",
			Handler:    _PaymentRequestService_Reissue_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "paymentSimulator/payment/service/paymentRequestReissueService.proto",
}
