// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: paymentSimulator/payment/paymentMakingCardService.proto

package payment

import (
	context "context"
	dto "github.com/Kenji-Uema/paymentSimulator/internal/domain/dto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PaymentMakingCardService_PayWithCard_FullMethodName = "/paymentSimulator.payment.v1.PaymentMakingCardService/PayWithCard"
)

// PaymentMakingCardServiceClient is the client API for PaymentMakingCardService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaymentMakingCardServiceClient interface {
	PayWithCard(ctx context.Context, in *dto.PayWithCardRequest, opts ...grpc.CallOption) (*dto.PayWithCardResponse, error)
}

type paymentMakingCardServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentMakingCardServiceClient(cc grpc.ClientConnInterface) PaymentMakingCardServiceClient {
	return &paymentMakingCardServiceClient{cc}
}

func (c *paymentMakingCardServiceClient) PayWithCard(ctx context.Context, in *dto.PayWithCardRequest, opts ...grpc.CallOption) (*dto.PayWithCardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(dto.PayWithCardResponse)
	err := c.cc.Invoke(ctx, PaymentMakingCardService_PayWithCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentMakingCardServiceServer is the server API for PaymentMakingCardService service.
// All implementations must embed UnimplementedPaymentMakingCardServiceServer
// for forward compatibility.
type PaymentMakingCardServiceServer interface {
	PayWithCard(context.Context, *dto.PayWithCardRequest) (*dto.PayWithCardResponse, error)
	mustEmbedUnimplementedPaymentMakingCardServiceServer()
}

// UnimplementedPaymentMakingCardServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaymentMakingCardServiceServer struct{}

func (UnimplementedPaymentMakingCardServiceServer) PayWithCard(context.Context, *dto.PayWithCardRequest) (*dto.PayWithCardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PayWithCard not implemented")
}
func (UnimplementedPaymentMakingCardServiceServer) mustEmbedUnimplementedPaymentMakingCardServiceServer() {
}
func (UnimplementedPaymentMakingCardServiceServer) testEmbeddedByValue() {}

// UnsafePaymentMakingCardServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentMakingCardServiceServer will
// result in compilation errors.
type UnsafePaymentMakingCardServiceServer interface {
	mustEmbedUnimplementedPaymentMakingCardServiceServer()
}

func RegisterPaymentMakingCardServiceServer(s grpc.ServiceRegistrar, srv PaymentMakingCardServiceServer) {
	// If the following call panics, it indicates UnimplementedPaymentMakingCardServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PaymentMakingCardService_ServiceDesc, srv)
}

func _PaymentMakingCardService_PayWithCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dto.PayWithCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentMakingCardServiceServer).PayWithCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentMakingCardService_PayWithCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentMakingCardServiceServer).PayWithCard(ctx, req.(*dto.PayWithCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PaymentMakingCardService_ServiceDesc is the grpc.ServiceDesc for PaymentMakingCardService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaymentMakingCardService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "paymentSimulator.payment.v1.PaymentMakingCardService",
	HandlerType: (*PaymentMakingCardServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PayWithCard",
			Handler:    _PaymentMakingCardService_PayWithCard_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "paymentSimulator/payment/paymentMakingCardService.proto",
}
