// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: paymentSimulator/payment/service/paymentMakingService.proto

package payment

import (
	context "context"
	dto "github.com/Kenji-Uema/paymentSimulator/internal/domain/dto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PaymentMakingService_PayWithCard_FullMethodName = "/paymentSimulator.payment.v1.PaymentMakingService/PayWithCard"
)

// PaymentMakingServiceClient is the client API for PaymentMakingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaymentMakingServiceClient interface {
	PayWithCard(ctx context.Context, in *dto.PayWithCardRequest, opts ...grpc.CallOption) (*dto.PayWithCardResponse, error)
}

type paymentMakingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentMakingServiceClient(cc grpc.ClientConnInterface) PaymentMakingServiceClient {
	return &paymentMakingServiceClient{cc}
}

func (c *paymentMakingServiceClient) PayWithCard(ctx context.Context, in *dto.PayWithCardRequest, opts ...grpc.CallOption) (*dto.PayWithCardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(dto.PayWithCardResponse)
	err := c.cc.Invoke(ctx, PaymentMakingService_PayWithCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentMakingServiceServer is the server API for PaymentMakingService service.
// All implementations must embed UnimplementedPaymentMakingServiceServer
// for forward compatibility.
type PaymentMakingServiceServer interface {
	PayWithCard(context.Context, *dto.PayWithCardRequest) (*dto.PayWithCardResponse, error)
	mustEmbedUnimplementedPaymentMakingServiceServer()
}

// UnimplementedPaymentMakingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaymentMakingServiceServer struct{}

func (UnimplementedPaymentMakingServiceServer) PayWithCard(context.Context, *dto.PayWithCardRequest) (*dto.PayWithCardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PayWithCard not implemented")
}
func (UnimplementedPaymentMakingServiceServer) mustEmbedUnimplementedPaymentMakingServiceServer() {}
func (UnimplementedPaymentMakingServiceServer) testEmbeddedByValue()                              {}

// UnsafePaymentMakingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentMakingServiceServer will
// result in compilation errors.
type UnsafePaymentMakingServiceServer interface {
	mustEmbedUnimplementedPaymentMakingServiceServer()
}

func RegisterPaymentMakingServiceServer(s grpc.ServiceRegistrar, srv PaymentMakingServiceServer) {
	// If the following call panics, it indicates UnimplementedPaymentMakingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PaymentMakingService_ServiceDesc, srv)
}

func _PaymentMakingService_PayWithCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(dto.PayWithCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentMakingServiceServer).PayWithCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentMakingService_PayWithCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentMakingServiceServer).PayWithCard(ctx, req.(*dto.PayWithCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PaymentMakingService_ServiceDesc is the grpc.ServiceDesc for PaymentMakingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaymentMakingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "paymentSimulator.payment.v1.PaymentMakingService",
	HandlerType: (*PaymentMakingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PayWithCard",
			Handler:    _PaymentMakingService_PayWithCard_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "paymentSimulator/payment/service/paymentMakingService.proto",
}
